language: ruby # don't install any environment
rvm: 2.6.3

# use bundler v2.x (https://docs.travis-ci.com/user/languages/ruby/#bundler-20)
before_install:
  - gem install bundler

cache: bundler

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      name: "Build project"
      script: bundle exec middleman build
    - stage: deploy
      name: "Deploy to Github Pages"
      script: bash ./deploy.sh
      if: (NOT type IN (pull_request)) AND (branch = master)

env:
  global:
  - ENCRYPTION_LABEL: "ddab409dc7f0"
